### 课程查询列表
POST {{content_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "",
  "publishStatus": ""
}

<> 2023-02-06T235812.200.json


### 新增课程接口