### 上传文件
POST {{media_host}}/media/upload/coursefile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="刘亦菲.jpg"
Content-Type: application/octet-stream

< F:/图片/本机照片/壁纸/刘亦菲.jpg



